### ISSUE TITLE
tailscaled.service: Failed with result 'exit-code'

### ISSUE THREAD

**Issue by bisraelsen** [tailscale-dev/deck-tailscale#10]
I'm getting an error when trying to install

```
(deck@steamdeck deck-tailscale)$ sudo bash tailscale.sh 
[sudo] password for deck: 
Getting version...got 1.50.1.
Downloading...done.
Installing...done.
Starting required services...
systemd-sysext is already enabled and active
Done.
Install complete. Starting tailscaled...
Job for tailscaled.service failed because the control process exited with error code.
See "systemctl status tailscaled.service" and "journalctl -xeu tailscaled.service" for details.
```

Using the first command shows:

```
(1)(deck@steamdeck deck-tailscale)$ systemctl status tailscaled.service
× tailscaled.service - Tailscale node agent
     Loaded: loaded (/etc/systemd/system/tailscaled.service; enabled; preset: disabled)
    Drop-In: /etc/systemd/system/tailscaled.service.d
             └─override.conf
     Active: failed (Result: exit-code) since Tue 2023-10-03 22:33:45 MDT; 1min 6s ago
       Docs: https://tailscale.com/kb/
    Process: 6419 ExecStartPre=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
    Process: 6449 ExecStart=/usr/sbin/tailscaled --state=/var/lib/tailscale/tailscaled.state --socket=/run/tailscale/tailscaled.sock --port=${PORT} $FLAGS (code=exited, status=2)
    Process: 6454 ExecStopPost=/usr/sbin/tailscaled --cleanup (code=exited, status=0/SUCCESS)
   Main PID: 6449 (code=exited, status=2)
        CPU: 260ms

Oct 03 22:33:45 steamdeck systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
Oct 03 22:33:45 steamdeck systemd[1]: Stopped Tailscale node agent.
Oct 03 22:33:45 steamdeck systemd[1]: tailscaled.service: Start request repeated too quickly.
Oct 03 22:33:45 steamdeck systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Oct 03 22:33:45 steamdeck systemd[1]: Failed to start Tailscale node agent.
```

**Comment by japawBlob** [comment]
Got same error

**Comment by Pjvw1106** [comment]
@legowerewolf - Here's a pastebin while I was using Steam Link to setup Tailscale. Copied from journalctl -f, hopefully this helps. Getting the same error as above. 

https://pastebin.com/cq3PZhpB

Oct 09 16:52:41 steamdeck tailscaled[10599]: logtail started
Oct 09 16:52:41 steamdeck tailscaled[10599]: Program starting: v1.50.1-tf45c02bfc-g36a20760a, Go 1.21.1: []string{"/usr/sbin/tailscaled", "--cleanup"}
Oct 09 16:52:41 steamdeck tailscaled[10599]: LogID: 626f24353f5315233a9f659d7bcc0a81ba85b9d0e2e969f3e27b217801bd0e7d
Oct 09 16:52:41 steamdeck tailscaled[10599]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Oct 09 16:52:41 steamdeck tailscaled[10599]: dns: [resolved-ping=yes rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=foreign ret=systemd-resolved]
Oct 09 16:52:41 steamdeck tailscaled[10599]: dns: using "systemd-resolved" mode
Oct 09 16:52:41 steamdeck tailscaled[10599]: creating dns cleanup: route ip+net: no such network interface
Oct 09 16:52:41 steamdeck tailscaled[10599]: deleting [-j ts-input] in filter/INPUT: running [/usr/bin/iptables -t filter -D INPUT -j ts-input --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-input':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10599]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10599]: deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/iptables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-forward':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10599]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10599]: deleting [-j ts-postrouting] in nat/POSTROUTING: running [/usr/bin/iptables -t nat -D POSTROUTING -j ts-postrouting --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-postrouting':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10599]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10599]: deleting [-j ts-input] in filter/INPUT: running [/usr/bin/ip6tables -t filter -D INPUT -j ts-input --wait]: exit status 2: ip6tables v1.8.8 (legacy): Couldn't load target `ts-input':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10599]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10599]: deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/ip6tables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: ip6tables v1.8.8 (legacy): Couldn't load target `ts-forward':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10599]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10599]: [RATELIMIT] format("deleting %v in %s/%s: %v")
Oct 09 16:52:41 steamdeck tailscaled[10599]: flushing log.
Oct 09 16:52:41 steamdeck tailscaled[10599]: logger closing down
Oct 09 16:52:41 steamdeck kernel: overlayfs: failed to resolve '/run/systemd/unit-extensions/0/opt': -2
Oct 09 16:52:41 steamdeck kernel: overlayfs: "xino" feature enabled using 3 upper inode bits.
Oct 09 16:52:41 steamdeck tailscaled[10629]: invalid value "" for flag -port: can't be the empty string
Oct 09 16:52:41 steamdeck tailscaled[10629]: Usage of /usr/sbin/tailscaled:
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -bird-socket string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             path of the bird unix socket
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -cleanup
Oct 09 16:52:41 steamdeck tailscaled[10629]:             clean up system state and exit
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -debug string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             listen address ([ip]:port) of optional debug server
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -no-logs-no-support
Oct 09 16:52:41 steamdeck tailscaled[10629]:             disable log uploads; this also disables any technical support
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -outbound-http-proxy-listen string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             optional [ip]:port to run an outbound HTTP proxy (e.g. "localhost:8080")
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -port value
Oct 09 16:52:41 steamdeck tailscaled[10629]:             UDP port to listen on for WireGuard and peer-to-peer traffic; 0 means automatically select (default 0)
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -socket string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             path of the service unix socket (default "/var/run/tailscale/tailscaled.sock")
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -socks5-server string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             optional [ip]:port to run a SOCK5 server (e.g. "localhost:1080")
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -state string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             absolute path of state file; use 'kube:<secret-name>' to use Kubernetes secrets or 'arn:aws:ssm:...' to store in AWS SSM; use 'mem:' to not store state and register as an ephemeral node. If empty and --statedir is provided, the default is <statedir>/tailscaled.state. Default: /var/lib/tailscale/tailscaled.state
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -statedir string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             path to directory for storage of config state, TLS certs, temporary incoming Taildrop files, etc. If empty, it's derived from --state when possible.
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -tun string
Oct 09 16:52:41 steamdeck tailscaled[10629]:             tunnel interface name; use "userspace-networking" (beta) to not use TUN (default "tailscale0")
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -verbose int
Oct 09 16:52:41 steamdeck tailscaled[10629]:             log verbosity level; 0 is default, 1 or higher are increasingly verbose
Oct 09 16:52:41 steamdeck tailscaled[10629]:   -version
Oct 09 16:52:41 steamdeck tailscaled[10629]:             print version information and exit
Oct 09 16:52:41 steamdeck systemd[1]: tailscaled.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 09 16:52:41 steamdeck kernel: overlayfs: failed to resolve '/run/systemd/unit-extensions/0/opt': -2
Oct 09 16:52:41 steamdeck kernel: overlayfs: "xino" feature enabled using 3 upper inode bits.
Oct 09 16:52:41 steamdeck tailscaled[10634]: logtail started
Oct 09 16:52:41 steamdeck tailscaled[10634]: Program starting: v1.50.1-tf45c02bfc-g36a20760a, Go 1.21.1: []string{"/usr/sbin/tailscaled", "--cleanup"}
Oct 09 16:52:41 steamdeck tailscaled[10634]: LogID: 626f24353f5315233a9f659d7bcc0a81ba85b9d0e2e969f3e27b217801bd0e7d
Oct 09 16:52:41 steamdeck tailscaled[10634]: logpolicy: using $STATE_DIRECTORY, "/var/lib/tailscale"
Oct 09 16:52:41 steamdeck tailscaled[10634]: dns: [resolved-ping=yes rc=nm resolved=nss nm-resolved=yes nm-safe=no resolv-conf-mode=foreign ret=systemd-resolved]
Oct 09 16:52:41 steamdeck tailscaled[10634]: dns: using "systemd-resolved" mode
Oct 09 16:52:41 steamdeck tailscaled[10634]: creating dns cleanup: route ip+net: no such network interface
Oct 09 16:52:41 steamdeck tailscaled[10634]: deleting [-j ts-input] in filter/INPUT: running [/usr/bin/iptables -t filter -D INPUT -j ts-input --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-input':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10634]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10634]: deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/iptables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-forward':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10634]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10634]: deleting [-j ts-postrouting] in nat/POSTROUTING: running [/usr/bin/iptables -t nat -D POSTROUTING -j ts-postrouting --wait]: exit status 2: iptables v1.8.8 (legacy): Couldn't load target `ts-postrouting':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10634]: Try `iptables -h' or 'iptables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10634]: deleting [-j ts-input] in filter/INPUT: running [/usr/bin/ip6tables -t filter -D INPUT -j ts-input --wait]: exit status 2: ip6tables v1.8.8 (legacy): Couldn't load target `ts-input':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10634]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10634]: deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/ip6tables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: ip6tables v1.8.8 (legacy): Couldn't load target `ts-forward':No such file or directory
Oct 09 16:52:41 steamdeck tailscaled[10634]: Try `ip6tables -h' or 'ip6tables --help' for more information.
Oct 09 16:52:41 steamdeck tailscaled[10634]: [RATELIMIT] format("deleting %v in %s/%s: %v")
Oct 09 16:52:41 steamdeck tailscaled[10634]: flushing log.
Oct 09 16:52:41 steamdeck tailscaled[10634]: logger closing down
Oct 09 16:52:41 steamdeck systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Oct 09 16:52:41 steamdeck systemd[1]: Failed to start Tailscale node agent.
Oct 09 16:52:42 steamdeck systemd[1]: tailscaled.service: Scheduled restart job, restart counter is at 5.
Oct 09 16:52:42 steamdeck systemd[1]: Stopped Tailscale node agent.
Oct 09 16:52:42 steamdeck systemd[1]: tailscaled.service: Start request repeated too quickly.
Oct 09 16:52:42 steamdeck systemd[1]: tailscaled.service: Failed with result 'exit-code'.
Oct 09 16:52:42 steamdeck systemd[1]: Failed to start Tailscale node agent.

**Comment by legowerewolf** [comment]
Hm. Is it something with iptables? I'll check my system tomorrow (hopefully) to see what version I'm running.

**Comment by Pjvw1106** [comment]
I started by following the original Tailscale guide from last year, got it working once then had issues, then found the Steam Deck plugin and came to your guide next. I've spent the better part of 3-4 hours today messing with it with no luck. Let me know what you find out.

**Comment by legowerewolf** [comment]
What do you mean by a plugin?

**Comment by Pjvw1106** [comment]
I'm sorry I should have provided better context, someone imlemented controls for this into a "Plugin" managed by a 3rd party software called "Decky", provides the ability to turn Tailscale on and off from the Steam Deck UI. Followed the links to your github from there.  

https://github.com/saumya-banthia/tailscale-control

**Comment by agherzan** [comment]
The relevant log here is:

```
 Oct 09 16:52:41 steamdeck tailscaled[10629]: invalid value "" for flag -port: can't be the empty string
 ```
 
 Remove your `/etc/default/tailscaled` file and rerun the installer script.

**Comment by legowerewolf** [comment]
With no further responses, I'm going to mark this as closed. If someone's having further issues, we can reopen or spawn a new issue.

**Comment by jiahzhang** [comment]
I'm having the same issue, what log should I paste?

**Comment by legowerewolf** [comment]
@jiahzhang try deleting /etc/default/tailscaled and re-running the script. Let me know if that does or doesn't work.

**Comment by jiahzhang** [comment]
Hey that worked, thought I tried that... thanks

**Comment by lwb-2021** [comment]
The question appears in my archlinux system
```
logtail started
Program starting: v1.58.2, Go 1.21.6: []string{"tailscaled", "--cleanup"}
LogID: 9a19b5a0f628bed4ef6436c05e5d5d186c5800d42f37cb150685f75674b27082
logpolicy: using system state directory "/var/lib/tailscale"
dns: [rc=nm resolved=nss nm-resolved=yes nm-resolved=no ret=direct]
dns: using "direct" mode
dns: using *dns.directManager
deleting [-j ts-input] in filter/INPUT: running [/usr/bin/iptables -t filter -D INPUT -j ts-input --wait]: exit status 2: iptables v1.8.10 (legacy): Couldn't load target `ts-input':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/iptables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: iptables v1.8.10 (legacy): Couldn't load target `ts-forward':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
deleting [-j ts-postrouting] in nat/POSTROUTING: running [/usr/bin/iptables -t nat -D POSTROUTING -j ts-postrouting --wait]: exit status 2: iptables v1.8.10 (legacy): Couldn't load target `ts-postrouting':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
deleting [-j ts-input] in filter/INPUT: running [/usr/bin/ip6tables -t filter -D INPUT -j ts-input --wait]: exit status 2: ip6tables v1.8.10 (legacy): Couldn't load target `ts-input':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
deleting [-j ts-forward] in filter/FORWARD: running [/usr/bin/ip6tables -t filter -D FORWARD -j ts-forward --wait]: exit status 2: ip6tables v1.8.10 (legacy): Couldn't load target `ts-forward':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
[RATELIMIT] format("deleting %v in %s/%s: %v")
flushing log.
logger closing down
```

**Comment by nekoneko-nya** [comment]
tailscale need to work with `tun.ko` and 'autofs4.ko'

**Comment by nekoneko-nya** [comment]
tailscale need to work with 'tun.ko' and 'autofs4.ko'
check your kernel conifgs:

> zcat /proc/config.gz | grep CONFIG_TUN
> zcat /proc/config.gz | grep CONFIG_AUTOFS_FS

if any of these configs is =m, try to probe it:

> sudo modprobe tun
> sudo modprobe autofs4
