### ISSUE TITLE
Bash command doesn’t work

### ISSUE THREAD

**Issue by driveformer** [tailscale-dev/deck-tailscale#18]
Just says “no such file or directory”. I’m going to look for a way around this, but your how to guide doesn’t work.

**Comment by legowerewolf** [comment]
To confirm, you:
- cloned the script to your Deck
- switched directories to the cloned repo
- ran `sudo bash tailscale.sh`

and got something about the file not being found?

Can you show us your terminal output?

**Comment by driveformer** [comment]
Hey Duncan!

I’m not sure ultimately what it was, after deleting the files and
redownloading it worked. Names weren’t different or anything so not sure
what happened. Also, your script in the guide only enables ssh but I’m
assuming most people will want it to accept routes so you can do things
like stream etc.

Thanks for getting to me so quickly!
Nick

**Comment by Phoenax77** [comment]
Hey, I'm having the exact same issues
