### ISSUE TITLE
Installation Fails without override.conf

### ISSUE THREAD

**Issue by bgulla** [tailscale-dev/deck-tailscale#8]
Upon a fresh install, the installation fails if `/etc/systemd/system/tailscaled.service.d/override.conf` does not exist.

Once I `touch /etc/systemd/system/tailscaled.service.d/override.conf` and run the installation again, it completes successfully. 

 
``` bash
(1)(deck@steamdeck ~)$ sudo bash tailscale.sh
Getting version...got 1.50.0.
Downloading...done.
Installing...cp: cannot stat 'override.conf': No such file or directory
```

**Comment by legowerewolf** [comment]
Huh, that's weird. I've never seen that error for the _destination_ file.

**Comment by MoaiGuy** [comment]
it does the same to me

**Comment by legowerewolf** [comment]
do you have the full repo there? or just the install script?

**Comment by MoaiGuy** [comment]
> do you have the full repo there? or just the install script?

Tried with just the script alone, then tried again with having the override.conf file too in the same place, no difference.

**Comment by legowerewolf** [comment]
so you've got tailscale.sh and override.conf on your desktop? then make sure you `cd` to your desktop and try running it again.

**Comment by legowerewolf** [comment]
Well, you've got to do the `tailscale up` command to get it on your network, but after that you should be good.

**Comment by MoaiGuy** [comment]
Nice, thanks again :D
